import { Hono } from "hono";
import { db } from "../lib/db.js";
import { upload, signedGet, signedPut, deleteObject } from "../lib/b2.js";
import { detectMediaType, finalizeMediaType, sanitizeFilenameForKey, ALLOWED_MIMES } from "../lib/media.js";

const app=new Hono();
app.get("/allowed-mimes",c=>c.json({mimes:ALLOWED_MIMES}));
app.get("/blob/:key{.+}",async c=>{const key=decodeURIComponent(c.req.param("key"));return c.redirect(await signedGet(c.env,key,300),302)});
app.post("/presign",async c=>{const b=await c.req.json().catch(()=>({}));if(!b.filename)return c.json({error:"missing_filename"},400);const key=`media/${crypto.randomUUID()}/${sanitizeFilenameForKey(b.filename)}`;return c.json({key,upload_url:await signedPut(c.env,key,900),method:"PUT"});});
app.post("/upload",async c=>{const len=Number(c.req.header("content-length")||0);if(len&&len>Number(c.env.MAX_UPLOAD_BYTES||104857600))return c.json({error:"file_too_large",max:Number(c.env.MAX_UPLOAD_BYTES||104857600)},413);let form;try{form=await c.req.raw.formData()}catch(e){return c.json({error:"expected_multipart",message:e.message},400)}const file=form.get("file");const postId=form.get("post_id")?String(form.get("post_id")):null;if(!(file instanceof File))return c.json({error:"missing_file"},400);if(file.size>Number(c.env.MAX_UPLOAD_BYTES||104857600))return c.json({error:"file_too_large",size:file.size,max:Number(c.env.MAX_UPLOAD_BYTES||104857600)},413);const bytes=new Uint8Array(await file.arrayBuffer()),d=await detectMediaType(bytes,file.type);if(!d.ok)return c.json({error:"unsupported_media",reason:d.reason,allowed:ALLOWED_MIMES},400);const sql=db(c.env);if(postId&&!(await sql`SELECT 1 FROM "Post" WHERE id=${postId}`)[0])return c.json({error:"post_not_found"},404);const type=finalizeMediaType(d.kind,file.name),key=`media/${crypto.randomUUID()}/${sanitizeFilenameForKey(file.name)}`;try{await upload(c.env,key,bytes,d.mime)}catch(e){return c.json({error:"storage_upload_failed",detail:e.message},502)}let row;try{row=(await sql`INSERT INTO "Media" (id,"postId",type,url,key,filename,"mimeType",size,"createdAt") VALUES(${crypto.randomUUID()},${postId},${type},${`/media/blob/${encodeURIComponent(key)}`},${key},${file.name},${d.mime},${file.size},NOW()) RETURNING id,"postId",type,url,key,filename,"mimeType",size,"createdAt"`)[0]}catch(e){try{await deleteObject(c.env,key)}catch{};return c.json({error:"media_persist_failed",detail:e.message},500)}return c.json({media:{id:row.id,post_id:row.postId,type:row.type,url:row.url,filename:row.filename,mime_type:row.mimeType,size:row.size,created_at:row.createdAt}},201)});
export default app;
