import { Hono } from "hono";
import { db } from "../lib/db.js";
import { signedGet } from "../lib/b2.js";

const app=new Hono(); const DEFAULT=20, MAX=100, DEPTH=3;
async function mediaFor(env,ids){ if(!ids.length)return []; const sql=db(env); const rows=await sql`SELECT id,"postId",type,url,key,filename,"mimeType",size,"createdAt" FROM "Media" WHERE id = ANY(${ids}) ORDER BY "createdAt" ASC`; return Promise.all(rows.map(async m=>({id:m.id,type:m.type,url:m.key?await signedGet(env,m.key,3600):m.url,filename:m.filename,mime_type:m.mimeType,size:m.size,created_at:m.createdAt}))); }
async function one(env,r){ return {...r,media:await mediaFor(env,(r.mediaIds||[]))}; }
async function fetchPost(env,id){ const sql=db(env); const rows=await sql`SELECT p.id,p.content,p."parentId",p.tags,p."createdAt",p."updatedAt",COALESCE((SELECT json_agg(json_build_object('id',m.id,'type',m.type,'key',m.key,'url',m.url,'filename',m.filename,'mimeType',m."mimeType",'size',m.size,'createdAt',m."createdAt") ORDER BY m."createdAt") FROM "Media" m WHERE m."postId"=p.id),'[]') media FROM "Post" p WHERE p.id=${id}`; if(!rows[0])return null; const r=rows[0]; const media=await Promise.all((r.media||[]).map(async m=>({id:m.id,type:m.type,url:m.key?await signedGet(env,m.key,3600):m.url,filename:m.filename,mime_type:m.mimeType,size:m.size,created_at:m.createdAt}))); return {id:r.id,content:r.content,parent_id:r.parentId,tags:r.tags||[],media,created_at:r.createdAt,updated_at:r.updatedAt}; }

app.post("/",async c=>{ const b=await c.req.json().catch(()=>({})); const content=typeof b.content==="string"?b.content.trim():null; const parentId=b.parentId||null; const tags=Array.isArray(b.tags)?b.tags.map(String).filter(Boolean).slice(0,10):[]; const mediaIds=Array.isArray(b.mediaIds)?b.mediaIds:[]; if(!content&&!mediaIds.length)return c.json({error:"empty_post",message:"content or media required"},400); const sql=db(c.env); if(parentId && !(await sql`SELECT 1 FROM "Post" WHERE id=${parentId}`)[0])return c.json({error:"parent_not_found"},404); const id=crypto.randomUUID(); const rows=await sql`INSERT INTO "Post" (id,content,"parentId",tags,"createdAt","updatedAt") VALUES(${id},${content},${parentId},${tags},NOW(),NOW()) RETURNING id,content,"parentId",tags,"createdAt","updatedAt"`; if(mediaIds.length) await sql`UPDATE "Media" SET "postId"=${id} WHERE id = ANY(${mediaIds})`; return c.json({post:await fetchPost(c.env,id)},201); });
app.get("/",async c=>{ const sql=db(c.env),limit=Math.min(MAX,Math.max(1,Number(c.req.query("limit"))||DEFAULT)),cursor=c.req.query("cursor")||null; const rows=cursor?await sql`SELECT p.id,p.content,p."parentId",p.tags,p."createdAt",p."updatedAt" FROM "Post" p WHERE p."parentId" IS NULL AND p.id < ${cursor} ORDER BY p."createdAt" DESC LIMIT ${limit+1}`:await sql`SELECT p.id,p.content,p."parentId",p.tags,p."createdAt",p."updatedAt" FROM "Post" p WHERE p."parentId" IS NULL ORDER BY p."createdAt" DESC LIMIT ${limit+1}`; const slice=rows.slice(0,limit); const posts=await Promise.all(slice.map(r=>fetchPost(c.env,r.id))); return {posts,next_cursor:rows.length>limit?slice.at(-1).id:null}; });
app.get("/search",async c=>{ const q=(c.req.query("q")||"").trim(),tag=(c.req.query("tag")||"").toLowerCase().trim(),type=c.req.query("type")||"",limit=Math.min(MAX,Math.max(1,Number(c.req.query("limit"))||DEFAULT)); if(!q&&!tag&&!type)return c.json({error:"missing_query",message:"supply at least one of q, tag, type"},400); const sql=db(c.env); let rows; if(q&&tag&&type)rows=await sql`SELECT p.id FROM "Post" p JOIN "Media" m ON m."postId"=p.id WHERE p.content ILIKE ${'%'+q+'%'} AND ${tag}=ANY(p.tags) AND m.type=${type} GROUP BY p.id ORDER BY MAX(p."createdAt") DESC LIMIT ${limit}`; else if(q&&tag)rows=await sql`SELECT p.id FROM "Post" p WHERE p.content ILIKE ${'%'+q+'%'} AND ${tag}=ANY(p.tags) ORDER BY p."createdAt" DESC LIMIT ${limit}`; else if(q)rows=await sql`SELECT p.id FROM "Post" p WHERE p.content ILIKE ${'%'+q+'%'} ORDER BY p."createdAt" DESC LIMIT ${limit}`; else if(tag)rows=await sql`SELECT p.id FROM "Post" p WHERE ${tag}=ANY(p.tags) ORDER BY p."createdAt" DESC LIMIT ${limit}`; else rows=await sql`SELECT DISTINCT p.id FROM "Post" p JOIN "Media" m ON m."postId"=p.id WHERE m.type=${type} ORDER BY p.id LIMIT ${limit}`; const posts=await Promise.all(rows.map(r=>fetchPost(c.env,r.id))); return {query:{q,tag:tag||null,type:type||null,limit},count:posts.length,posts}; });
app.get("/tags/:tag",async c=>{ const tag=c.req.param("tag").toLowerCase().trim(),limit=Math.min(MAX,Math.max(1,Number(c.req.query("limit"))||DEFAULT)),sql=db(c.env),rows=await sql`SELECT id FROM "Post" WHERE ${tag}=ANY(tags) ORDER BY "createdAt" DESC LIMIT ${limit}`,posts=await Promise.all(rows.map(r=>fetchPost(c.env,r.id))); return {tag,count:posts.length,posts}; });
app.get("/:id",async c=>{const post=await fetchPost(c.env,c.req.param("id"));if(!post)return c.json({error:"not_found"},404);const sql=db(c.env),rows=await sql`WITH RECURSIVE thread AS (SELECT id,"parentId",content,tags,"createdAt","updatedAt",1 depth FROM "Post" WHERE id=${post.id} UNION ALL SELECT p.id,p."parentId",p.content,p.tags,p."createdAt",p."updatedAt",t.depth+1 FROM "Post" p JOIN thread t ON p."parentId"=t.id WHERE t.depth < ${DEPTH}) SELECT id,"parentId" FROM thread WHERE id<>${post.id} ORDER BY depth,"createdAt"`;const replies=await Promise.all(rows.map(r=>fetchPost(c.env,r.id)));return {post:{...post,replies}};});
app.patch("/:id",async c=>{const b=await c.req.json().catch(()=>({})),id=c.req.param("id"),content=typeof b.content==="string"?b.content.trim():undefined,tags=Array.isArray(b.tags)?b.tags.map(String).filter(Boolean).slice(0,10):undefined,sql=db(c.env);if(!(await sql`SELECT 1 FROM "Post" WHERE id=${id}`)[0])return c.json({error:"not_found"},404);if(content!==undefined&&tags!==undefined)await sql`UPDATE "Post" SET content=${content||null},tags=${tags},"updatedAt"=NOW() WHERE id=${id}`;else if(content!==undefined)await sql`UPDATE "Post" SET content=${content||null},"updatedAt"=NOW() WHERE id=${id}`;else if(tags!==undefined)await sql`UPDATE "Post" SET tags=${tags},"updatedAt"=NOW() WHERE id=${id}`;return {post:await fetchPost(c.env,id)};});
app.delete("/:id",async c=>{const id=c.req.param("id"),sql=db(c.env),p=await sql`SELECT id FROM "Post" WHERE id=${id}`;if(!p[0])return c.json({error:"not_found"},404);const replies=await sql`SELECT id FROM "Post" WHERE "parentId"=${id}`;if(replies.length)return c.json({error:"has_replies",message:"delete or move replies before deleting this post",reply_ids:replies.map(x=>x.id)},409);const media=await sql`SELECT key FROM "Media" WHERE "postId"=${id}`;await sql`DELETE FROM "Post" WHERE id=${id}`;return c.body(null,204);});
export default app;
